# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cogs.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cogs.proto',
  package='Scrapers',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\ncogs.proto\x12\x08Scrapers\"B\n\x04\x43ogs\x12\x0e\n\x06source\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12\x0e\n\x06\x62ranch\x18\x03 \x01(\t\x12\x0c\n\x04\x63ogs\x18\x04 \x01(\tb\x06proto3'
)




_COGS = _descriptor.Descriptor(
  name='Cogs',
  full_name='Scrapers.Cogs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='source', full_name='Scrapers.Cogs.source', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='date', full_name='Scrapers.Cogs.date', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='branch', full_name='Scrapers.Cogs.branch', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cogs', full_name='Scrapers.Cogs.cogs', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=90,
)

DESCRIPTOR.message_types_by_name['Cogs'] = _COGS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Cogs = _reflection.GeneratedProtocolMessageType('Cogs', (_message.Message,), {
  'DESCRIPTOR' : _COGS,
  '__module__' : 'cogs_pb2'
  # @@protoc_insertion_point(class_scope:Scrapers.Cogs)
  })
_sym_db.RegisterMessage(Cogs)


# @@protoc_insertion_point(module_scope)
